spring.application.name=GestorTareas

# ===============================
# CONEXIÓN A ORACLE
# ===============================
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=gestor
spring.datasource.password=gestor
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# SERVER
# ===============================
server.port=8080
